name: Create SingBOX Files

on:
  push:
    branches:
      - main
      
  schedule:
    - cron: '*/120 * * * *'
jobs:
  create_files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set URL
        run: echo "URL=https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/singbox/sfi_sfa.json" >> $GITHUB_ENV

      - name: Delete existing SingBOX files
        run: rm -f SingBoxs/*
        
      - name: Create SingBOX directory
        run: mkdir -p SingBoxs


      - name: Create SingBOX files
        run: |
          content=$(curl -s ${{ env.URL }})
          while IFS= read -r line; do
            username=$(echo "$line" | cut -d ',' -f 1)
            echo "$content" > "SingBoxs/${username}"
          done < Users.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Create SingBOX files"
          git push
