name: Create SingBOX Files

on:
  push:
    branches:
      - main
      
  schedule:
    - cron: '*/120 * * * *'
jobs:
  create_files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set URL
        run: echo "URL=https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/singbox/sfi_sfa.json" >> $GITHUB_ENV

      - name: Check for changes to Users.txt
        id: check_changes
        run: |
          changed=$(git diff --name-only HEAD^ HEAD | grep -c "Users.txt")
          echo "::set-output name=changed::$changed"
          
      - name: Create SingBOX directory
        if: steps.check_changes.outputs.changed == '1'
        run: mkdir -p SingBoxs

      - name: Delete existing SingBOX files
        if: steps.check_changes.outputs.changed == '1'
        run: rm -f SingBoxs/*

      - name: Create SingBOX files
        if: steps.check_changes.outputs.changed == '1'
        run: |
          content=$(curl -s ${{ env.URL }})
          while IFS= read -r line; do
            username=$(echo "$line" | cut -d ',' -f 1)
            
            if [ "$number" -gt 0 ]; then
              echo "$content" > "SingBoxs/${username}-Reality-Singbox"
            fi
          done < Users.txt

      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == '1'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Create SingBOX files"
          git push
