name: Create SingBOX Files

on:
  push:
    branches:
      - main
      
  schedule:
    - cron: '*/120 * * * *'
jobs:
  create_files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set URL
        run: echo "URL=https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/singbox/sfasfi/tuicLite.json" >> $GITHUB_ENV

      - name: Delete existing SingBOX files
        run: rm -f SingBoxs/*
        
      - name: Create SingBOX directory
        run: mkdir -p SingBoxs


      - name: Create SingBOX files
        run: |
          content=$(curl -s ${{ env.URL }} | sed 's/رایگان//g')
          while IFS= read -r line; do
            username=$(echo "$line" | cut -d ',' -f 1)
            echo "$content" > "SingBoxs/${username}"
          done < Users.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update files" || exit 0  # Exit successfully if there's nothing to commit
          git push --force
