name: Create Configs

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytz requests regex jdatetime

    - name: Remove SUB directory
      run: rm -rf SUB

    - name: Run V2ray-Creator
      run: python Scripts/CreateV2ray.py  # Replace with your script's filename
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update files" || exit 0  # Exit successfully if there's nothing to commit
        git push
