name: Create Configs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/120 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
      TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz requests regex jdatetime telethon

      - name: Remove SUB directory
        run: rm -rf SUB

      - name: Run REALITY-Creator
        run: python Scripts/REALITY-Creator.py  
      
      - name: Run WORKER-Creator
        run: python Scripts/WORKER-Creator.py  

      - name: Run SIngBox-Creator
        run: python Scripts/SingBox-Creator.py  
          
      - name: Run TUIC-Creator
        run: python Scripts/TUIC-Creator.py

      - name: Run WIRE-Creator
        run: python Scripts/WIRE-Creator.py
      
      - name: Run WIRE-Creator
        run: python Scripts/ShadowSocks-Creator.py

          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update files" || exit 0  # Exit successfully if there's nothing to commit
          git push --force
