name: Create Configs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/120 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz requests regex jdatetime

      - name: Remove SUB directory
        run: rm -rf SUB
      - name: Run Downloader of collected links
        run: python Scripts/Download_Collected_Links.py  
        env:
          GITHUB_TOKEN: ${{ secrets.PERIVATE_TOKEN_VIEWER }}  # Inject the secret as an environment variable
          
      - name: Run Profile-Creator
        run: python Scripts/Profile_Creator.py  
        env:
          GITHUB_TOKEN: ${{ secrets.PERIVATE_TOKEN_VIEWER }}  # Inject the secret as an environment variable
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update files" || exit 0  # Exit successfully if there's nothing to commit
          git push --force
